# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdflyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdflyDemo
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'Alamofire', '4.9.1'
  pod 'CryptoSwift', '~> 0.8.3'
  pod 'GZIP', '~> 1.2'
end
